import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, BookOpen, CheckCircle2, ClipboardList, LayoutDashboard, Menu, RefreshCw, Search, Settings, ShieldCheck, Users, X } from 'lucide-react';
import { AdminAuthGuard } from './AdminAuthGuard';
import { adminService } from '../../services/adminService';
import { AdminIdentity, AdminSummary, NeedRequest, RequestStatus, Story, UserProfile } from '../../types';

type ModuleId = 'overview' | 'requests' | 'users' | 'stories' | 'sessions' | 'safety' | 'settings';
const navItems: Array<{ id: ModuleId; label: string; icon: React.ElementType }> = [
  { id: 'overview', label: 'Tổng quan', icon: LayoutDashboard },
  { id: 'requests', label: 'Yêu cầu trợ giúp', icon: ClipboardList },
  { id: 'users', label: 'Người dùng', icon: Users },
  { id: 'stories', label: 'Duyệt câu chuyện', icon: BookOpen },
  { id: 'sessions', label: 'Phiên hỗ trợ', icon: Activity },
  { id: 'safety', label: 'Trung tâm an toàn', icon: ShieldCheck },
  { id: 'settings', label: 'Cài đặt', icon: Settings },
];
const statusLabels: Record<RequestStatus, string> = { open: 'Đang mở', matched: 'Đã ghép', accepted: 'Đã nhận', in_progress: 'Đang xử lý', completed: 'Hoàn thành', cancelled: 'Đã hủy' };
const statusClasses: Record<RequestStatus, string> = { open: 'admin-badge admin-badge-blue', matched: 'admin-badge admin-badge-purple', accepted: 'admin-badge admin-badge-amber', in_progress: 'admin-badge admin-badge-amber', completed: 'admin-badge admin-badge-green', cancelled: 'admin-badge admin-badge-red' };

function Metric({ label, value, detail, icon: Icon, tone }: { label: string; value: number; detail: string; icon: React.ElementType; tone: string }) {
  return <div className="admin-panel admin-metric"><div className={`admin-metric-icon ${tone}`}><Icon className="h-5 w-5" /></div><div><p className="admin-eyebrow">{label}</p><p className="admin-metric-value">{value.toLocaleString('vi-VN')}</p><p className="admin-muted">{detail}</p></div></div>;
}

function Overview({ summary }: { summary: AdminSummary }) {
  const total = Object.values(summary.requests).reduce((sum, count) => sum + count, 0);
  return <div className="space-y-5"><Heading title="Tổng quan hệ thống" subtitle="Theo dõi sức khỏe cộng đồng và các điểm cần xử lý." /><div className="admin-grid-metrics"><Metric label="Yêu cầu đang mở" value={summary.requests.open} detail={`${total} yêu cầu tổng`} icon={ClipboardList} tone="admin-icon-blue" /><Metric label="Đang hỗ trợ" value={summary.requests.in_progress + summary.requests.accepted} detail="Phiên cần theo dõi" icon={Activity} tone="admin-icon-amber" /><Metric label="Hoàn thành" value={summary.requests.completed} detail="Ca hỗ trợ thành công" icon={CheckCircle2} tone="admin-icon-green" /><Metric label="Cảnh báo an toàn" value={summary.safety.unresolved} detail="Cần kiểm tra thủ công" icon={AlertTriangle} tone="admin-icon-red" /></div><section className="admin-panel p-5 sm:p-6"><div className="admin-section-heading"><div><h2 className="admin-section-title">Hoạt động gần đây</h2><p className="admin-muted">Dữ liệu vận hành mới nhất</p></div></div><div className="mt-4 divide-y divide-slate-200/60">{summary.recentActivity.length ? summary.recentActivity.map((item) => <div className="admin-activity" key={item.id}><span className={`admin-activity-dot admin-dot-${item.tone}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{item.label}</p><p className="truncate text-xs text-slate-500">{item.detail}</p></div><span className="shrink-0 text-xs text-slate-400">{item.timestamp}</span></div>) : <div className="admin-empty">Chưa có hoạt động để hiển thị</div>}</div></section></div>;
}
function Heading({ title, subtitle }: { title: string; subtitle: string }) { return <div className="admin-page-heading"><div><p className="admin-kicker">SYSTEM OPERATIONS</p><h1 className="admin-title">{title}</h1><p className="admin-muted mt-1">{subtitle}</p></div><span className="admin-status"><span className="admin-status-dot" /> Connected</span></div>; }

function DataModule({ module }: { module: Exclude<ModuleId, 'overview' | 'sessions' | 'safety' | 'settings'> }) {
  const [requests, setRequests] = useState<NeedRequest[]>([]); const [stories, setStories] = useState<Story[]>([]); const [users, setUsers] = useState<UserProfile[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { if (module === 'requests') setRequests(await adminService.getRequests()); if (module === 'stories') setStories(await adminService.getStories()); if (module === 'users') setUsers(await adminService.getUsers()); } catch (loadError: any) { setError(loadError?.message || 'Không thể tải dữ liệu.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [module]);
  const titles = { requests: ['Yêu cầu trợ giúp', 'Cập nhật trạng thái và theo dõi rủi ro'], users: ['Người dùng', 'Quản lý thành viên và độ tin cậy'], stories: ['Duyệt câu chuyện', 'Kiểm tra consent và nội dung công khai'] } as const;
  const [title, subtitle] = titles[module]; const term = search.toLowerCase();
  const requestRows = requests.filter((item) => `${item.title} ${item.requesterName} ${item.locationName}`.toLowerCase().includes(term)); const storyRows = stories.filter((item) => `${item.title} ${item.authorName} ${item.theme}`.toLowerCase().includes(term)); const userRows = users.filter((item) => `${item.name} ${item.email || ''} ${item.role}`.toLowerCase().includes(term));
  return <div className="space-y-5"><Heading title={title} subtitle={subtitle} /><section className="admin-panel p-5 sm:p-6"><div className="admin-toolbar"><div className="admin-search"><Search className="h-4 w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Tìm trong ${title.toLowerCase()}...`} /></div><button className="admin-button admin-button-secondary" onClick={load}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /> Làm mới</button></div>{error ? <div className="admin-error">{error}<button className="admin-link" onClick={load}>Thử lại</button></div> : loading ? <div className="admin-loading"><RefreshCw className="h-6 w-6 animate-spin" /> Đang tải dữ liệu...</div> : module === 'requests' ? <div className="admin-record-list">{requestRows.map((item) => <div className="admin-record" key={item.id}><div className="min-w-0 flex-1"><strong>{item.title}</strong><small>{item.requesterName} · {item.locationName}</small></div><select className="admin-select" value={item.status} onChange={async (event) => { const status = event.target.value as RequestStatus; await adminService.updateRequestStatus(item.id, status); setRequests((current) => current.map((row) => row.id === item.id ? { ...row, status } : row)); }} aria-label={`Trạng thái ${item.title}`}>{Object.keys(statusLabels).map((status) => <option value={status} key={status}>{statusLabels[status as RequestStatus]}</option>)}</select><span className={statusClasses[item.status]}>{statusLabels[item.status]}</span></div>)}</div> : module === 'stories' ? <div className="admin-record-list">{storyRows.map((item) => <div className="admin-record" key={item.id}><div className="min-w-0 flex-1"><strong>{item.title}</strong><small>{item.authorName} · {item.theme}</small></div><button className={`admin-button ${item.isPublicConsent ? 'admin-button-secondary' : 'admin-button-primary'}`} onClick={async () => { const isPublic = !item.isPublicConsent; await adminService.moderateStory(item.id, isPublic); setStories((current) => current.map((row) => row.id === item.id ? { ...row, isPublicConsent: isPublic } : row)); }}>{item.isPublicConsent ? 'Đang công khai' : 'Duyệt công khai'}</button></div>)}</div> : <div className="admin-record-list">{userRows.map((item) => <div className="admin-record" key={item.id}><div className="admin-user-row"><img src={item.avatar} alt="" /><div><strong>{item.name}</strong><small>{item.email || 'Không có email'} · {item.role}</small></div></div><span className="admin-badge admin-badge-green">{item.isHelperAvailable ? 'Sẵn sàng' : 'Đang bận'}</span></div>)}</div>}{!loading && !error && (module === 'requests' ? requestRows.length : module === 'stories' ? storyRows.length : userRows.length) === 0 && <div className="admin-empty">Không có dữ liệu phù hợp.</div>}</section></div>;
}

function StaticModule({ module }: { module: Exclude<ModuleId, 'overview' | 'requests' | 'users' | 'stories'> }) { const labels = { sessions: ['Phiên hỗ trợ', 'Theo dõi match, interaction và lifecycle'], safety: ['Trung tâm an toàn', 'Xử lý các cảnh báo cần can thiệp'], settings: ['Cài đặt', 'Quyền hạn và cấu hình hệ thống'] }; const [title, subtitle] = labels[module]; return <div className="space-y-5"><Heading title={title} subtitle={subtitle} /><section className="admin-panel admin-module-empty"><div className="admin-empty-icon"><ShieldCheck className="h-6 w-6" /></div><h2>Module đang được kết nối</h2><p>API dữ liệu cho khu vực này sẽ được bổ sung theo schema session, safety và audit. Quyền truy cập vẫn được kiểm tra bằng Custom Claims.</p></section></div>; }

export const AdminDashboard: React.FC = () => <AdminAuthGuard>{(identity) => <Workspace identity={identity} />}</AdminAuthGuard>;
function Workspace({ identity }: { identity: AdminIdentity }) { const [module, setModule] = useState<ModuleId>('overview'); const [summary, setSummary] = useState<AdminSummary | null>(null); const [mobileOpen, setMobileOpen] = useState(false); const [loading, setLoading] = useState(true); const refresh = () => { setLoading(true); adminService.getSummary().then(setSummary).finally(() => setLoading(false)); }; useEffect(refresh, []); const active = navItems.find((item) => item.id === module) || navItems[0]; const Icon = active.icon; return <div className="admin-app"><aside className={`admin-sidebar ${mobileOpen ? 'is-open' : ''}`}><div className="admin-brand"><div className="admin-brand-mark"><ShieldCheck className="h-5 w-5" /></div><div><strong>HUMAN MAP</strong><span>OPERATIONS</span></div><button className="admin-close-mobile" onClick={() => setMobileOpen(false)}><X className="h-5 w-5" /></button></div><nav className="admin-nav">{navItems.map((item) => { const ItemIcon = item.icon; return <button className={`admin-nav-item ${module === item.id ? 'is-active' : ''}`} key={item.id} onClick={() => { setModule(item.id); setMobileOpen(false); }}><ItemIcon className="h-[18px] w-[18px]" /><span>{item.label}</span></button>; })}</nav><div className="admin-sidebar-foot"><div className="admin-user-avatar">{(identity.email || 'A').slice(0, 1).toUpperCase()}</div><div className="min-w-0"><strong className="block truncate">{identity.email || 'Admin'}</strong><span>{identity.role}</span></div></div></aside><div className="admin-main"><header className="admin-topbar"><button className="admin-menu-mobile" onClick={() => setMobileOpen(true)}><Menu className="h-5 w-5" /></button><div className="admin-breadcrumb"><Icon className="h-4 w-4" /><span>{active.label}</span></div><button className="admin-icon-button" onClick={refresh} title="Làm mới dữ liệu"><RefreshCw className={loading ? 'animate-spin' : ''} /></button></header><main className="admin-content">{loading && !summary ? <div className="admin-loading"><RefreshCw className="h-6 w-6 animate-spin" /> Đang tải dữ liệu tổng quan...</div> : summary ? module === 'overview' ? <Overview summary={summary} /> : module === 'requests' || module === 'users' || module === 'stories' ? <DataModule module={module} /> : <StaticModule module={module} /> : <div className="admin-panel p-8">Không thể tải dữ liệu dashboard.</div>}</main></div></div>; }
